apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: oci://ghcr.io/prometheus-community/chart
    releaseName: monitoring
    namespace: monitoring
    valuesFile: ./values/prometheus.yaml
    includeCRDs: true
  - name: vector
    repo: https://helm.vector.dev
    releaseName: vector
    namespace: monitoring
    valuesFile: ./values/vector.yaml
  - name: victoria-logs-single
    repo: https://victoriametrics.github.io/helm-charts/
    releaseName: victoria-logs
    namespace: monitoring
    valuesFile: ./values/victoria-logs.yaml
    


resources:
  - ./resources/namespace.yaml
