apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy
  namespace: monitoring
  labels:    
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy
  namespaceSelector:
    matchNames:
      - "envoy-gateway-system"
  endpoints:
  - port: "http-19001"
    path: "/stats/prometheus"
