---
apiVersion: v1
kind: ConfigMap
metadata:
  name: http-load-generator-hosts
data:
  hosts.json: |
    [
            {
                "host_name": "group1",
                "base_url": "http://group1:3003"
            },
            {
                "host_name": "group2",
                "base_url": "http://group2:3003"
            },
            {
                "host_name": "group3",
                "base_url": "http://group3:3003"
            },
            {
                "host_name": "group4",
                "base_url": "http://group4:3003"
            },
            {
                "host_name": "group5",
                "base_url": "http://group5:3003"
            },
            {
                "host_name": "group6",
                "base_url": "http://group6:3003"
            },
            {
                "host_name": "group7",
                "base_url": "http://group7:3003"
            },
            {
                "host_name": "group8",
                "base_url": "http://group8:3003"
            },
            {
                "host_name": "group9",
                "base_url": "http://group9:3003"
            },
            {
                "host_name": "group10",
                "base_url": "http://group10:3003"
            },
            {
                "host_name": "group11",
                "base_url": "http://group11:3003"
            },
            {
                "host_name": "group12",
                "base_url": "http://group12:3003"
            },
            {
                "host_name": "group13",
                "base_url": "http://group13:3003"
            },
            {
                "host_name": "group14",
                "base_url": "http://group14:3003"
            },
            {
                "host_name": "group15",
                "base_url": "http://group15:3003"
            },
            {
                "host_name": "group16",
                "base_url": "http://group16:3003"
            },
            {
                "host_name": "group17",
                "base_url": "http://group17:3003"
            },
            {
                "host_name": "group18",
                "base_url": "http://group18:3003"
            },
            {
                "host_name": "group19",
                "base_url": "http://group19:3003"
            },
            {
                "host_name": "group20",
                "base_url": "http://group20:3003"
            },
            {
                "host_name": "landau",
                "base_url": "http://landau:3003"
            }
    ]
---
apiVersion: v1
kind: Service
metadata:
  name: http-load-generator
spec:
  type: ClusterIP
  selector:
    app: http-load-generator
  ports:
    - name: metrics
      targetPort: 3002
      port: 3002
---
apiVersion: v1
kind: Pod
metadata:
  name: http-load-generator
  labels: 
    app: http-load-generator
spec:
  volumes:
    - name: creds-key
      secret:
        secretName: creds-key
        items:
          - key: creds-key
            path: creds-key
    - name: hosts
      configMap:
        name: http-load-generator-hosts
    - name: credentials
      emptyDir: {}
  initContainers:
    - name: setup-credentials
      image: alpine:3.20
      command:
        - /bin/sh
        - -ec
        - |
          apk add --no-cache wget openssl unzip

          ls -la /etc/secrets
          cat /etc/secrets/creds-key

          wget -q \
            -O /tmp/creds.zip.enc \
            https://github.com/landaudiogo/cec-infrastructure/raw/refs/heads/master/nixos/secrets/creds.zip.enc

          openssl enc -d -aes-256-cbc -pbkdf2 -salt \
            -in /tmp/creds.zip.enc \
            -out /tmp/creds.zip \
            -pass file:/etc/secrets/creds-key

          unzip -o /tmp/creds.zip -d /tmp/credentials

          # BROKER SPECIFIC
          mv /tmp/credentials/creds/admins/landau/* /etc/credentials
          ls -la /etc/credentials
      volumeMounts:
        - name: credentials
          mountPath: /etc/credentials
        - name: creds-key
          mountPath: /etc/secrets
          readOnly: true
  containers:
    - name: http-load-generator
      image: dclandau/cec-http-load-generator:f2941da
      args:
        - --brokers
        - "kafka-1:9094,kafka-2:9094,kafka-3:9094"
        - --topic
        - "experiment-document"
        - --consumer-wait-before-send 
        - "60"
        - --hosts-file
        - /etc/http-load-generator/hosts.json
        - --num-generations
        - "8" 
        - --requestor-lag 
        - "5" 
        - --requestor-retries
        - "0"
        - --requestor-max-in-flight
        - "80" 
        - --stable-rate-duration
        - "60"
      env:
        - name: RUST_LOG
          value: info
        - name: GROUP_ID
          valueFrom:
            secretKeyRef:
              name: demo-stress
              key: GROUP_ID
        - name: MIN_BATCH_SIZE
          valueFrom:
            secretKeyRef:
              name: demo-stress
              key: MIN_BATCH_SIZE
        - name: MAX_BATCH_SIZE
          valueFrom:
            secretKeyRef:
              name: demo-stress
              key: MAX_BATCH_SIZE
      volumeMounts:
        - name: credentials
          mountPath: /auth
        - name: hosts
          mountPath: /etc/http-load-generator/
