# helm install prometheus -n monitoring \
#   --create-namespace \
#   prometheus-community/kube-prometheus-stack \
#   -f prometheus-values.yaml

coreDns:
  serviceMonitor:
    port: http-metrics
  service:
    port: 10055
    targetPort: 10055

prometheus:
  prometheusSpec:
    enableOTLPReceiver: true
  service:
    type: NodePort
    nodePort: 30954
    
alertmanager:
  enabled: false

grafana:
  operator: true
  enabled: true
  service:
    type: NodePort
    nodePort: 30007
  adminUser: admin
  adminPassword: admin-password

kubelet:
  serviceMonitor:
    interval: 15s
    cAdvisorMetricRelabelings: null
