{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "panels": [
  { "title": "System Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(experiment_producer_event_count_total{topic=\"experiment\"}[5s]))",
     "legendFormat": "events"
    }
   ]
  },
  {
   "title": "HTTP Load Targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "http_load_generator_target_request_rate",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  { "title": "Notification Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Notification Endpoint (Error)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(notifications_service_response_count_total{response_type!~\"Ok\"}[$__range]))) by (response_type)",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "# Groups Completed Notifications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH \n\tall_groups AS (\n\t\tSELECT \n\t\t\t'group'|| unnest as group_id\n\t\tFROM \n\t\t\tunnest(array[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])\n\t\tUNION ALL\n\t\tSELECT 'landau'\n\t),\n\tmissing_groups AS (\n\t\tSELECT \n\t\t\tag.group_id\n\t\tFROM\n\t\t\tdemo.notification_ground_truth gt\n\t\tCROSS JOIN \n\t\t\tall_groups ag\n\t\tLEFT JOIN\n\t\t\tdemo.notification n\n\t\t\tON gt.measurement_id = n.measurement_id AND gt.experiment_id = n.experiment_id\n\t\t\t\tAND n.group_id = ag.group_id\n\t\tWHERE \n\t\t\tgt.insert_timestamp BETWEEN $__timeFrom() AND $__timeTo()    \n\t\t\tAND n.group_id IS NULL\n\t\tGROUP BY \n\t\t\tag.group_id\n\t),\n\tcompleted_groups AS (\n\t\tSELECT \n\t\t\t*\n\t\tFROM \n\t\t\tall_groups\n\t\tEXCEPT ALL\n\t\tSELECT \n\t\t\t*\n\t\tFROM \n\t\t\tmissing_groups\n\t)\nSELECT COUNT(*) FROM completed_groups\n\t"
    }
   ]
  },
  {
   "title": "# Groups Missing Notifications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH \n\tall_groups AS (\n\t\tSELECT \n\t\t\t'group'|| unnest as group_id\n\t\tFROM \n\t\t\tunnest(array[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])\n\t\tUNION ALL\n\t\tSELECT 'landau'\n\t),\n\tmissing_groups AS (\n\t\tSELECT \n\t\t\tag.group_id\n\t\tFROM\n\t\t\tdemo.notification_ground_truth gt\n\t\tCROSS JOIN \n\t\t\tall_groups ag\n\t\tLEFT JOIN\n\t\t\tdemo.notification n\n\t\t\tON gt.measurement_id = n.measurement_id AND gt.experiment_id = n.experiment_id\n\t\t\t\tAND n.group_id = ag.group_id\n\t\tWHERE \n\t\t\tgt.insert_timestamp BETWEEN $__timeFrom() AND $__timeTo()  \n\t\t\tAND n.group_id IS NULL\n\t\tGROUP BY \n\t\t\tag.group_id\n\t)\nSELECT \n\tCOUNT(*)\nFROM \n\tmissing_groups"
    }
   ]
  },
  {
   "title": "Notification Latency Histogram",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH\n\tnotified AS (\n\t\tSELECT \n\t\t  experiment_id, measurement_id, latency\n\t\tFROM \n\t\t  demo.notification\n  ),\n  ground_truth AS (\n    SELECT \n      experiment_id, measurement_id, insert_timestamp\n    FROM \n      demo.notification_ground_truth\n  )\nSELECT \n\tCASE \n\t\tWHEN t1.bucket < 10 THEN\n\t\t\t'[' || CAST(t1.bucket AS TEXT) || '; ' || CAST(t1.bucket+1 AS TEXT) || ']'\n\t\tELSE\n\t\t\t'[' || CAST(t1.bucket AS TEXT) || '; ' || '+∞[' \n\tEND AS bucket,\n\tSUM(bucket_count) AS bucket_count\nFROM (\n\tSELECT\n\t\tbucket, COUNT(*) as bucket_count\n\tFROM \n\t\t(\n\t\t\tSELECT\n\t\t\t\twidth_bucket(latency, array[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) as bucket\n\t\t\tFROM \n\t\t\t  ground_truth gt\n\t\t\tLEFT JOIN\n\t\t\t\tnotified n\n\t\t\tON gt.measurement_id = n.measurement_id AND gt.experiment_id = n.experiment_id\n\t\t\tWHERE \n\t\t\t\tn.measurement_id IS NOT NULL\n\t\t\t\tAND gt.insert_timestamp BETWEEN $__timeFrom() AND $__timeTo()\n\t\t) AS buckets\n\tGROUP BY buckets.bucket\n\tUNION ALL \n\tSELECT \n\t\tunnest as bucket, 0 as bucket_count \n\tFROM \n\t\tunnest(array[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])\n) as t1\nGROUP BY bucket\nORDER BY CAST(bucket AS int)\n"
    }
   ]
  },
  {
   "title": "# Groups < 10s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- GROUPS WITH ALL LATENCIES < 10s\nSELECT COUNT(*) FROM (\nSELECT \n\tgroup_id\nFROM \n\tdemo.notification_ground_truth gt\nLEFT JOIN\n\tdemo.notification n\n\tON n.experiment_id = gt.experiment_id AND n.measurement_id = gt.measurement_id\nWHERE \n\tgt.insert_timestamp BETWEEN $__timeFrom() AND $__timeTo() \n\tAND n.group_id IS NOT NULL\nGROUP BY\n\tgroup_id\nEXCEPT ALL\nSELECT \n\tgroup_id\nFROM \n  \tdemo.notification_ground_truth gt\nLEFT JOIN\n\tdemo.notification n\n\tON gt.measurement_id = n.measurement_id AND gt.experiment_id = n.experiment_id\nWHERE \n\tn.measurement_id IS NOT NULL\n\tAND gt.insert_timestamp BETWEEN $__timeFrom() AND $__timeTo()  \n  \tAND n.latency > 10\nGROUP BY\n\tn.group_id\n) t1;"
    }
   ]
  },
  {
   "title": "# Groups > 10s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM (\n\tSELECT \n\t\tgroup_id\n\tFROM \n\t\tdemo.notification_ground_truth gt\n\tLEFT JOIN\n\t\tdemo.notification n\n\t\tON gt.measurement_id = n.measurement_id AND gt.experiment_id = n.experiment_id\n\tWHERE \n\t\tn.measurement_id IS NOT NULL\n\t\tAND gt.insert_timestamp BETWEEN $__timeFrom() AND $__timeTo() \n\t\tAND n.latency > 10\n\tGROUP BY\n\t\tn.group_id\n) as t1;"
    }
   ]
  },
  { "title": "REST statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Temperature (Ok)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      http_load_generator_response_count_total{endpoint=\"/temperature\", response_type=\"Ok\"}[$__range]\n    )\n  )\n)",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "OutOfBounds (Ok)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      http_load_generator_response_count_total{endpoint=\"/temperature/out-of-bounds\", response_type=\"Ok\"}[$__range]\n    )\n  )\n)",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Response Time Histogram",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_load_generator_response_rtt_histogram_bucket[$__range]))) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Temperature (Error)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (response_type) (\n  round(\n    increase(\n      http_load_generator_response_count_total{endpoint=\"/temperature\", response_type!~\"Ok\"}[$__range]\n    )\n  )\n)",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "OutOfBounds (Error)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (response_type) (\n  round(\n    increase(\n      http_load_generator_response_count_total{endpoint=\"/temperature/out-of-bounds\", response_type!~\"Ok\"}[$__range]\n    )\n  )\n)",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  { "title": "Infrastructure Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  rate(node_cpu_seconds_total{mode!=\"idle\", job=\"infrastructure-costs\"}[$__range])\n) \n/ on (instance) count by (instance) (node_cpu_seconds_total{mode=\"idle\", job=\"infrastructure-costs\"})\n* 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"infrastructure-costs\"} \n- on (instance) avg_over_time(node_memory_MemAvailable_bytes{job=\"infrastructure-costs\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Group View",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "group",
    "query": "group1, group2, group3, group4, group5, group6, group7, group8, group9, group10, group11, group12, group13, group14, group15, group16, group17, group18, group19, group20, landau"
   },
   { "name": "topic", "query": "experiment,test-experiment" }
  ]
 },
 "panels": [
  { "title": "System Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(experiment_producer_event_count_total{topic=\"$topic\"}[5s]))",
     "legendFormat": "events"
    }
   ]
  },
  {
   "title": "HTTP Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "http_load_generator_target_request_rate{host_name=\"$group\"}",
     "legendFormat": "target"
    },
    {
     "expr": "http_load_generator_effective_request_rate{host_name=\"$group\"}",
     "legendFormat": "real"
    }
   ]
  },
  { "title": "Notification Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Notification Endpoint (Error)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(notifications_service_response_count_total{group=\"$group\", response_type!~\"Ok\"}[$__range]))",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "# Required Notifications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(*) \nFROM \n  demo.notification_ground_truth\nWHERE \n  insert_timestamp BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "# Notifications Missing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH\n\tnotified AS (\n\t\tSELECT \n\t\t  experiment_id, measurement_id\n\t\tFROM \n\t\t  demo.notification\n\t\tWHERE\n\t\t  group_id = '$group'\n  ),\n  ground_truth AS (\n    SELECT \n      experiment_id, measurement_id, insert_timestamp\n    FROM \n      demo.notification_ground_truth\n  )\nSELECT \n  COUNT(*)\nFROM \n  ground_truth gt\nLEFT JOIN\n\tnotified n\nON gt.measurement_id = n.measurement_id AND gt.experiment_id = n.experiment_id\nWHERE \n\tn.measurement_id IS NULL\n\tAND gt.insert_timestamp BETWEEN $__timeFrom() AND $__timeTo() "
    }
   ]
  },
  {
   "title": "Notification Latency Histogram",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH\n\tnotified AS (\n\t\tSELECT \n\t\t  experiment_id, measurement_id, latency\n\t\tFROM \n\t\t  demo.notification\n\t\tWHERE\n\t\t  group_id = '$group'\n  ),\n  ground_truth AS (\n    SELECT \n      experiment_id, measurement_id, insert_timestamp\n    FROM \n      demo.notification_ground_truth\n  )\nSELECT \n\tCASE \n\t\tWHEN t1.bucket < 10 THEN\n\t\t\t'[' || CAST(t1.bucket AS TEXT) || '; ' || CAST(t1.bucket+1 AS TEXT) || ']'\n\t\tELSE\n\t\t\t'[' || CAST(t1.bucket AS TEXT) || '; ' || '+∞[' \n\tEND AS bucket,\n\tSUM(bucket_count) AS bucket_count\nFROM (\n\tSELECT\n\t\tbucket, COUNT(*) as bucket_count\n\tFROM \n\t\t(\n\t\t\tSELECT\n\t\t\t\twidth_bucket(latency, array[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) as bucket\n\t\t\tFROM \n\t\t\t  ground_truth gt\n\t\t\tLEFT JOIN\n\t\t\t\tnotified n\n\t\t\tON gt.measurement_id = n.measurement_id AND gt.experiment_id = n.experiment_id\n\t\t\tWHERE \n\t\t\t\tn.measurement_id IS NOT NULL\n\t\t\t\tAND gt.insert_timestamp BETWEEN $__timeFrom() AND $__timeTo()\n\t\t) AS buckets\n\tGROUP BY buckets.bucket\n\tUNION ALL \n\tSELECT \n\t\tunnest as bucket, 0 as bucket_count \n\tFROM \n\t\tunnest(array[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])\n) as t1\nGROUP BY bucket\nORDER BY CAST(bucket AS int)\n"
    }
   ]
  },
  {
   "title": "# Notifications < 10s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH\n\tnotified AS (\n\t\tSELECT \n\t\t  experiment_id, measurement_id, latency\n\t\tFROM \n\t\t  demo.notification\n\t\tWHERE\n\t\t  group_id = '$group'\n  ),\n  ground_truth AS (\n    SELECT \n      experiment_id, measurement_id, insert_timestamp\n    FROM \n      demo.notification_ground_truth\n  )\nSELECT \n  COUNT(*)\nFROM \n  ground_truth gt\nLEFT JOIN\n\tnotified n\nON gt.measurement_id = n.measurement_id AND gt.experiment_id = n.experiment_id\nWHERE \n\tn.measurement_id IS NOT NULL\n\tAND gt.insert_timestamp BETWEEN $__timeFrom() AND $__timeTo() \n  AND n.latency < 10"
    }
   ]
  },
  {
   "title": "# Notifications > 10s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH\n\tnotified AS (\n\t\tSELECT \n\t\t  experiment_id, measurement_id, latency\n\t\tFROM \n\t\t  demo.notification\n\t\tWHERE\n\t\t  group_id = '$group'\n  ),\n  ground_truth AS (\n    SELECT \n      experiment_id, measurement_id, insert_timestamp\n    FROM \n      demo.notification_ground_truth\n  )\nSELECT \n  COUNT(*)\nFROM \n  ground_truth gt\nLEFT JOIN\n\tnotified n\nON gt.measurement_id = n.measurement_id AND gt.experiment_id = n.experiment_id\nWHERE \n\tn.measurement_id IS NOT NULL\n\tAND gt.insert_timestamp BETWEEN $__timeFrom() AND $__timeTo() \n  AND n.latency > 10"
    }
   ]
  },
  { "title": "REST Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Temperature (Ok)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(http_load_generator_response_count_total{host_name=\"${group}\", endpoint=\"/temperature\", response_type=\"Ok\"}[$__range]))",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "OutOfBounds (Ok)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(http_load_generator_response_count_total{host_name=\"${group}\", endpoint=\"/temperature/out-of-bounds\", response_type=\"Ok\"}[$__range]))",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Response Time Histogram",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(http_load_generator_response_rtt_histogram_bucket{host_name=\"${group}\"}[$__range]))) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Temperature (Error)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(http_load_generator_response_count_total{host_name=\"${group}\", endpoint=\"/temperature\", response_type!~\"Ok\"}[$__range]))",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "OutOfBounds (Error)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(http_load_generator_response_count_total{host_name=\"${group}\", endpoint=\"/temperature/out-of-bounds\", response_type!~\"Ok\"}[$__range]))",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  { "title": "Infrastructure Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$group:.+\", job=\"infrastructure-costs\"}[$__range])) / \n  count(node_cpu_seconds_total{mode=\"idle\", instance=~\"$group:.+\", job=\"infrastructure-costs\"})\n) * 100 ",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Average Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$group:.+\", job=\"infrastructure-costs\"} - avg_over_time(node_memory_MemAvailable_bytes{instance=~\"$group:.+\", job=\"infrastructure-costs\"}[$__range])",
     "legendFormat": "memory"
    }
   ]
  }
 ]
}
{
 "title": "Error Overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Notification Endpoint (Error)",
   "type": "stat",
   "gridPos": { "h": 20, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host_name, response_type) (round(increase(notifications_service_response_count_total{response_type!~\"Ok\"}[$__range])))",
     "legendFormat": "{{host_name}} {{response_type}}"
    }
   ]
  },
  {
   "title": "Groups Missing Notifications",
   "type": "table",
   "gridPos": { "h": 20, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH \n\tall_groups AS (\n\t\tSELECT \n\t\t\t'group'|| unnest as group_id \n\t\tFROM \n\t\t\tunnest(array[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])\n\t\tUNION ALL\n\t\tSELECT 'landau'\n\t),\n\tmissing_groups AS (\n\t\tSELECT \n\t\t\tag.group_id\n\t\tFROM\n\t\t\tdemo.notification_ground_truth gt\n\t\tCROSS JOIN \n\t\t\tall_groups ag\n\t\tLEFT JOIN\n\t\t\tdemo.notification n\n\t\t\tON gt.measurement_id = n.measurement_id AND gt.experiment_id = n.experiment_id\n\t\t\t\tAND n.group_id = ag.group_id\n\t\tWHERE \n\t\t\tgt.insert_timestamp BETWEEN $__timeFrom() AND $__timeTo()  \n\t\t\tAND n.group_id IS NULL\n\t\tGROUP BY \n\t\t\tag.group_id\n\t)\nSELECT \n\tgroup_id\nFROM \n\tmissing_groups\nORDER BY \n\tCASE\n\t\tWHEN regexp_replace(group_id, '[a-z]', '', 'g') != '' THEN\n\t\t\tCAST(regexp_replace(group_id, '[a-z]', '', 'g') AS INTEGER)\n\t\tELSE\n\t\t\t0\n\tEND"
    }
   ]
  },
  {
   "title": "# Groups > 10s",
   "type": "table",
   "gridPos": { "h": 20, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "\nSELECT \n\tgroup_id\nFROM \n\tdemo.notification_ground_truth gt\nLEFT JOIN\n\tdemo.notification n\n\tON gt.measurement_id = n.measurement_id AND gt.experiment_id = n.experiment_id\nWHERE \n\tn.measurement_id IS NOT NULL\n\tAND gt.insert_timestamp BETWEEN $__timeFrom() AND $__timeTo() \n\tAND n.latency > 10\nGROUP BY\n\tn.group_id\nORDER BY \n\tCASE\n\t\tWHEN regexp_replace(n.group_id, '[a-z]', '', 'g') != '' THEN\n\t\t\tCAST(regexp_replace(n.group_id, '[a-z]', '', 'g') AS INTEGER)\n\t\tELSE\n\t\t\t0\n\tEND"
    }
   ]
  },
  {
   "title": "Temperature (Error)",
   "type": "stat",
   "gridPos": { "h": 20, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host_name) (\n  round(\n    increase(\n      http_load_generator_response_count_total{endpoint=\"/temperature\", response_type!~\"Ok\"}[$__range]\n    )\n  )\n)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Out of Bounds (Error)",
   "type": "stat",
   "gridPos": { "h": 20, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host_name) (\n  round(\n    increase(\n      http_load_generator_response_count_total{endpoint=\"/temperature/out-of-bounds\", response_type!~\"Ok\"}[$__range]\n    )\n  )\n)",
     "legendFormat": "{{host_name}}"
    }
   ]
  }
 ]
}