apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/notifications-service.yaml
  - ./resources/experiment-producer.yaml
  - ./resources/http-load-generator.yaml
